#
# Your Crowdin credentials
#
# create your own API credential config file in $HOME/.crowdin.yaml
# call this file by using:
# crowdin <command> --identity 'path-to-user-credentials-file'

"preserve_hierarchy": true


files: [
{
    "source": "/language/en/*.php",
    "translation": "/language/%two_letters_code%/%original_file_name%",
},
{
    "source": "/language/en/email/*.txt",
    "translation": "/language/%two_letters_code%/email/%original_file_name%",
}
]
