preserve_hierarchy: true
commit_message: "[ci skip]"
files:
  - source: /language/en/*.php
    translation: /language/%two_letters_code%/%original_file_name%
  - source: /language/en/email/*.txt
    translation: /language/%two_letters_code%/email/%original_file_name%
