services:
    skouat.ppde.ipn_listener:
        class: skouat\ppde\controller\ipn_listener
        arguments:
            - '@config'
            - '@service_container'
            - '@language'
            - '@notification_manager'
            - '@skouat.ppde.controller'
            - '@skouat.ppde.controller.admin.transactions'
            - '@request'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    skouat.ppde.controller:
        class: skouat\ppde\controller\main_controller
        arguments:
            - '@auth'
            - '@config'
            - '@service_container'
            - '@ext.manager'
            - '@controller.helper'
            - '@language'
            - '@skouat.ppde.entity.currency'
            - '@skouat.ppde.entity.donation_pages'
            - '@skouat.ppde.entity.transactions'
            - '@skouat.ppde.operator.currency'
            - '@skouat.ppde.operator.donation_pages'
            - '@skouat.ppde.operator.transactions'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    skouat.ppde.controller.admin.currency:
        class: skouat\ppde\controller\admin_currency_controller
        arguments:
            - '@service_container'
            - '@language'
            - '@log'
            - '@skouat.ppde.operator.currency'
            - '@request'
            - '@template'
            - '@user'

    skouat.ppde.controller.admin.donation_pages:
        class: skouat\ppde\controller\admin_donation_pages_controller
        arguments:
            - '@service_container'
            - '@language'
            - '@log'
            - '@skouat.ppde.operator.donation_pages'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'

    skouat.ppde.controller.admin.overview:
        class: skouat\ppde\controller\admin_overview_controller
        arguments:
            - '@auth'
            - '@cache'
            - '@config'
            - '@language'
            - '@log'
            - '@skouat.ppde.controller'
            - '@skouat.ppde.controller.admin.transactions'
            - '@request'
            - '@template'
            - '@user'
            - '%core.php_ext%'

    skouat.ppde.controller.admin.settings:
        class: skouat\ppde\controller\admin_settings_controller
        arguments:
            - '@config'
            - '@service_container'
            - '@language'
            - '@skouat.ppde.controller'
            - '@skouat.ppde.operator.currency'
            - '@request'
            - '@template'
            - '@user'

    skouat.ppde.controller.admin.transactions:
        class: skouat\ppde\controller\admin_transactions_controller
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@config'
            - '@service_container'
            - '@language'
            - '@log'
            - '@skouat.ppde.operator.transactions'
            - '@request'
            - '@template'
            - '@user'
            - '%core.adm_relative_path%'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%skouat.ppde.tables.ppde_transactions%'
