services:
    skouat.ppde.notification.type.admin_donation_received:
        class: skouat\ppde\notification\type\admin_donation_received
        shared: false # service MUST not be shared for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }

    skouat.ppde.notification.type.donor_donation_received:
        class: skouat\ppde\notification\type\donor_donation_received
        shared: false # service MUST not be shared for this to work!
        arguments:
            - '@dbal.conn'
            - '@language'
            - '@user'
            - '@auth'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
